{
  "cveId": "CVE-2024-32879",
  "title": "social-auth-app-django Improper Handling of Case Sensitivity vulnerability",
  "description": "Python Social Auth is a social authentication/registration mechanism. Prior to version 5.4.1, due to default case-insensitive collation in MySQL or MariaDB databases, third-party authentication user IDs are not case-sensitive and could cause different IDs to match. This issue has been addressed by a fix released in version 5.4.1. An immediate workaround would be to change collation of the affected field.",
  "publishedDate": "2024-04-24T19:42:14.642000+00:00",
  "lastModifiedDate": "2024-08-02T02:20:35.665000+00:00",
  "severity": "MEDIUM",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:C/C:L/I:L/A:N",
      "baseScore": 4.9,
      "baseSeverity": "MEDIUM"
    }
  ],
  "epss": {
    "score": 0.0012,
    "percentile": 32.61
  },
  "riskScore": 32,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["python-social-auth"],
    "products": ["social-app-django"]
  },
  "references": [
    {
      "url": "https://github.com/python-social-auth/social-app-django/security/advisories/GHSA-2gr8-3wc7-xhj3",
      "source": "https://github.com/python-social-auth/social-app-django/security/advisories/GHSA-2gr8-3wc7-xhj3",
      "tags": ["x_refsource_CONFIRM"]
    },
    {
      "url": "https://github.com/python-social-auth/social-app-django/pull/566",
      "source": "https://github.com/python-social-auth/social-app-django/pull/566",
      "tags": ["x_refsource_MISC"]
    },
    {
      "url": "https://github.com/python-social-auth/social-app-django/commit/31c3e0c7edb187004d8abbde7e9c4f7ef9098138",
      "source": "https://github.com/python-social-auth/social-app-django/commit/31c3e0c7edb187004d8abbde7e9c4f7ef9098138",
      "tags": ["x_refsource_MISC"]
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-178", "CWE-303"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2024/32xxx/CVE-2024-32879.json",
        "lastModified": "2024-08-02T02:20:35.665000+00:00"
      }
    ]
  }
}
