{
  "cveId": "CVE-2025-32414",
  "title": "CVE-2025-32414: In libxml2 before 2.13.8 and 2.14.x before 2.14.2, out-of-bounds memory access can occur in the Pyth...",
  "description": "In libxml2 before 2.13.8 and 2.14.x before 2.14.2, out-of-bounds memory access can occur in the Python API (Python bindings) because of an incorrect return value. This occurs in xmlPythonFileRead and xmlPythonFileReadRaw because of a difference between bytes and characters.",
  "publishedDate": "2025-04-08T00:00:00+00:00",
  "lastModifiedDate": "2025-04-09T14:57:02.635000+00:00",
  "severity": "MEDIUM",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:L/AC:H/PR:N/UI:N/S:C/C:L/I:L/A:L",
      "baseScore": 5.6,
      "baseSeverity": "MEDIUM"
    }
  ],
  "epss": {
    "score": 0.0002,
    "percentile": 2.661
  },
  "riskScore": 36,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["xmlsoft"],
    "products": ["libxml2"]
  },
  "references": [
    {
      "url": "https://gitlab.gnome.org/GNOME/libxml2/-/issues/889",
      "source": "",
      "tags": []
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-393"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2025/32xxx/CVE-2025-32414.json",
        "lastModified": "2025-04-09T14:57:02.635000+00:00"
      }
    ]
  }
}
