{
  "cveId": "CVE-2025-32908",
  "title": "Libsoup: denial of service on libsoup through http/2 server",
  "description": "A flaw was found in libsoup. The HTTP/2 server in libsoup may not fully validate the values of pseudo-headers :scheme, :authority, and :path, which may allow a user to cause a denial of service (DoS).",
  "publishedDate": "2025-04-14T14:00:30.423000+00:00",
  "lastModifiedDate": "2025-06-11T11:03:52.135000+00:00",
  "severity": "HIGH",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "baseScore": 7.5,
      "baseSeverity": "HIGH"
    }
  ],
  "epss": {
    "score": 0.0006,
    "percentile": 17.61
  },
  "riskScore": 43,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["red hat"],
    "products": [
      "red hat enterprise linux 9",
      "red hat enterprise linux 6",
      "red hat enterprise linux 10",
      "red hat enterprise linux 8",
      "red hat enterprise linux 7"
    ]
  },
  "references": [
    {
      "url": "https://access.redhat.com/errata/RHSA-2025:7505",
      "source": "RHSA-2025:7505",
      "tags": ["vendor-advisory", "x_refsource_REDHAT"]
    },
    {
      "url": "https://access.redhat.com/security/cve/CVE-2025-32908",
      "source": "",
      "tags": ["vdb-entry", "x_refsource_REDHAT"]
    },
    {
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2359343",
      "source": "RHBZ#2359343",
      "tags": ["issue-tracking", "x_refsource_REDHAT"]
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-115"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2025/32xxx/CVE-2025-32908.json",
        "lastModified": "2025-06-11T11:03:52.135000+00:00"
      }
    ]
  }
}
