{
  "cveId": "CVE-2024-31904",
  "title": "IBM App Connect Enterprise denial of service",
  "description": "IBM App Connect Enterprise 11.0.0.1 through 11.0.0.25 and 12.0.1.0 through 12.0.12.0 integration nodes could allow an authenticated user to cause a denial of service due to an uncaught exception.  IBM X-Force ID:  289647.",
  "publishedDate": "2024-05-22T18:34:39.881000+00:00",
  "lastModifiedDate": "2024-08-02T01:59:50.282000+00:00",
  "severity": "MEDIUM",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
      "baseScore": 6.5,
      "baseSeverity": "MEDIUM"
    }
  ],
  "epss": {
    "score": 0.0012,
    "percentile": 32.202
  },
  "riskScore": 40,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["ibm"],
    "products": ["app connect enterprise"]
  },
  "references": [
    {
      "url": "https://www.ibm.com/support/pages/node/7154607",
      "source": "",
      "tags": ["vendor-advisory"]
    },
    {
      "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/289647",
      "source": "",
      "tags": ["vdb-entry"]
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-248"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2024/31xxx/CVE-2024-31904.json",
        "lastModified": "2024-08-02T01:59:50.282000+00:00"
      }
    ]
  }
}
