{
  "cveId": "CVE-2024-27133",
  "title": "Insufficient sanitization in MLflow leads to XSS when running a recipe that uses an untrusted dataset.",
  "description": "Insufficient sanitization in MLflow leads to XSS when running a recipe that uses an untrusted dataset. This issue leads to a client-side RCE when running the recipe in Jupyter Notebook. The vulnerability stems from lack of sanitization over dataset table fields.",
  "publishedDate": "2024-02-23T22:00:33.124000+00:00",
  "lastModifiedDate": "2024-08-22T18:01:49.002000+00:00",
  "severity": "HIGH",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "baseScore": 7.5,
      "baseSeverity": "HIGH"
    }
  ],
  "epss": {
    "score": 0.0021,
    "percentile": 43.92
  },
  "riskScore": 37,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": [],
    "products": []
  },
  "references": [
    {
      "url": "https://research.jfrog.com/vulnerabilities/mlflow-untrusted-dataset-xss-jfsa-2024-000631932/",
      "source": "",
      "tags": []
    },
    {
      "url": "https://github.com/mlflow/mlflow/pull/10893",
      "source": "",
      "tags": []
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-79"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2024/27xxx/CVE-2024-27133.json",
        "lastModified": "2024-08-22T18:01:49.002000+00:00"
      }
    ]
  }
}
