{
  "cveId": "CVE-2025-47712",
  "title": "Nbd: nbdkit: integer overflow triggers an assertion resulting in denial of service",
  "description": "A flaw exists in the nbdkit \"blocksize\" filter that can be triggered by a specific type of client request. When a client requests block status information for a very large data range, exceeding a certain limit, it causes an internal error in the nbdkit, leading to a denial of service.",
  "publishedDate": "2025-06-09T05:58:41.198000+00:00",
  "lastModifiedDate": "2025-06-09T18:24:05.328000+00:00",
  "severity": "MEDIUM",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
      "baseScore": 4.3,
      "baseSeverity": "MEDIUM"
    }
  ],
  "epss": {
    "score": 0.0004,
    "percentile": 12.548
  },
  "riskScore": 36,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["red hat"],
    "products": [
      "red hat enterprise linux 9",
      "red hat enterprise linux 7",
      "red hat enterprise linux 10",
      "red hat enterprise linux 8 advanced virtualization",
      "red hat enterprise linux 8"
    ]
  },
  "references": [
    {
      "url": "https://access.redhat.com/security/cve/CVE-2025-47712",
      "source": "",
      "tags": ["vdb-entry", "x_refsource_REDHAT"]
    },
    {
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2365724",
      "source": "RHBZ#2365724",
      "tags": ["issue-tracking", "x_refsource_REDHAT"]
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-190"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2025/47xxx/CVE-2025-47712.json",
        "lastModified": "2025-06-09T18:24:05.328000+00:00"
      }
    ]
  }
}
