{
  "cveId": "CVE-2024-8354",
  "title": "Qemu-kvm: usb: assertion failure in usb_ep_get()",
  "description": "A flaw was found in QEMU. An assertion failure was present in the usb_ep_get() function in hw/net/core.c when trying to get the USB endpoint from a USB device. This flaw may allow a malicious unprivileged guest user to crash the QEMU process on the host and cause a denial of service condition.",
  "publishedDate": "2024-09-19T10:45:06.191000+00:00",
  "lastModifiedDate": "2025-05-21T07:59:38.128000+00:00",
  "severity": "MEDIUM",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
      "baseScore": 5.5,
      "baseSeverity": "MEDIUM"
    }
  ],
  "epss": {
    "score": 0.0001,
    "percentile": 0.256
  },
  "riskScore": 33,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["red hat"],
    "products": [
      "red hat enterprise linux 9",
      "red hat enterprise linux 7",
      "red hat enterprise linux 10",
      "red hat enterprise linux 6",
      "red hat enterprise linux 8 advanced virtualization",
      "red hat enterprise linux 8"
    ]
  },
  "references": [
    {
      "url": "https://access.redhat.com/security/cve/CVE-2024-8354",
      "source": "",
      "tags": ["vdb-entry", "x_refsource_REDHAT"]
    },
    {
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2313497",
      "source": "RHBZ#2313497",
      "tags": ["issue-tracking", "x_refsource_REDHAT"]
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-617"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2024/8xxx/CVE-2024-8354.json",
        "lastModified": "2025-05-21T07:59:38.128000+00:00"
      }
    ]
  }
}
