{
  "cveId": "CVE-2025-47711",
  "title": "Nbdkit: nbdkit-server: off-by-one error when processing block status may lead to a denial of service",
  "description": "There's a flaw in the nbdkit server when handling responses from its plugins regarding the status of data blocks. If a client makes a specific request for a very large data range, and a plugin responds with an even larger single block, the nbdkit server can encounter a critical internal error, leading to a denial-of-service.",
  "publishedDate": "2025-06-09T06:03:47.063000+00:00",
  "lastModifiedDate": "2025-06-09T18:19:57.680000+00:00",
  "severity": "MEDIUM",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
      "baseScore": 4.3,
      "baseSeverity": "MEDIUM"
    }
  ],
  "epss": {
    "score": 0.0004,
    "percentile": 12.62
  },
  "riskScore": 36,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["red hat"],
    "products": [
      "red hat enterprise linux 9",
      "red hat enterprise linux 7",
      "red hat enterprise linux 10",
      "red hat enterprise linux 8 advanced virtualization",
      "red hat enterprise linux 8"
    ]
  },
  "references": [
    {
      "url": "https://access.redhat.com/security/cve/CVE-2025-47711",
      "source": "",
      "tags": ["vdb-entry", "x_refsource_REDHAT"]
    },
    {
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2365687",
      "source": "RHBZ#2365687",
      "tags": ["issue-tracking", "x_refsource_REDHAT"]
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-193"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2025/47xxx/CVE-2025-47711.json",
        "lastModified": "2025-06-09T18:19:57.680000+00:00"
      }
    ]
  }
}
